# Teletun Configuration

# Message Transport Settings
message_transport:
  type: telegram # telegram или vk

  # Telegram Settings
  telegram:
    api_id: 12345678
    api_hash: your_api_hash
    peer_username: your_peer_username
    session_string: optional_session_string
    session_name: telegram_transport

  # VK Settings
  vk:
    access_token: your_vk_access_token
    peer_id: 123456789
    api_version: 5.131

# Data Transport Settings
data_transport:
  type: socks # tun или socks

  # TUN Settings
  tun:
    src_ip: 10.8.0.2
    dst_ip: 10.8.0.1
    mask: 255.255.255.0
    mtu: 1500
    interface_name: teletun

  # SOCKS Settings
  socks:
    proxy_host: 127.0.0.1
    proxy_port: 9050
    target_host: example.com
    target_port: 80

# General Settings
general:
  debug: false
  log_level: INFO
